import {
  siAngular,
  siAnsible,
  siApache,
  siApachekafka,
  siApachemaven,
  siBootstrap,
  siC,
  siCloudflare,
  siCplusplus,
  siDart,
  siDjango,
  siDocker,
  siDotnet,
  siElasticsearch,
  siElixir,
  siExpress,
  siFastapi,
  siFigma,
  siFirebase,
  siFlask,
  siFlutter,
  siGit,
  siGithub,
  siGithubactions,
  siGitlab,
  siGnubash,
  siGo,
  siGooglecloud,
  siGradle,
  siGraphql,
  siJenkins,
  siJira,
  siJupyter,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLinux,
  siLua,
  siMongodb,
  siMysql,
  siNestjs,
  siNetlify,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNpm,
  siNumpy,
  siOpenjdk,
  siPandas,
  siPhp,
  siPnpm,
  siPostgresql,
  siPostman,
  siPrisma,
  siPytorch,
  siPython,
  siR,
  siRaspberrypi,
  siReact,
  siRedis,
  siRuby,
  siRubyonrails,
  siRust,
  siScala,
  siSpring,
  siSqlite,
  siSupabase,
  siSvelte,
  siSwagger,
  siSwift,
  siTailwindcss,
  siTensorflow,
  siTerraform,
  siTypescript,
  siVercel,
  siVite,
  siVuedotjs,
  siWebpack,
  siYarn,
  type SimpleIcon,
} from 'simple-icons'

export const techIcons = {
  angular: siAngular,
  ansible: siAnsible,
  apache: siApache,
  'apache-kafka': siApachekafka,
  'apache-maven': siApachemaven,
  bash: siGnubash,
  bootstrap: siBootstrap,
  c: siC,
  cloudflare: siCloudflare,
  'c-plus-plus': siCplusplus,
  dart: siDart,
  django: siDjango,
  docker: siDocker,
  dotnet: siDotnet,
  elasticsearch: siElasticsearch,
  elixir: siElixir,
  express: siExpress,
  fastapi: siFastapi,
  figma: siFigma,
  firebase: siFirebase,
  flask: siFlask,
  flutter: siFlutter,
  git: siGit,
  github: siGithub,
  'github-actions': siGithubactions,
  gitlab: siGitlab,
  go: siGo,
  'google-cloud': siGooglecloud,
  gradle: siGradle,
  graphql: siGraphql,
  java: siOpenjdk,
  jenkins: siJenkins,
  jira: siJira,
  jupyter: siJupyter,
  kotlin: siKotlin,
  kubernetes: siKubernetes,
  laravel: siLaravel,
  linux: siLinux,
  lua: siLua,
  mongodb: siMongodb,
  mysql: siMysql,
  nestjs: siNestjs,
  netlify: siNetlify,
  nextjs: siNextdotjs,
  nginx: siNginx,
  nodejs: siNodedotjs,
  npm: siNpm,
  numpy: siNumpy,
  pandas: siPandas,
  php: siPhp,
  pnpm: siPnpm,
  postgresql: siPostgresql,
  postman: siPostman,
  prisma: siPrisma,
  python: siPython,
  pytorch: siPytorch,
  r: siR,
  'raspberry-pi': siRaspberrypi,
  react: siReact,
  redis: siRedis,
  ruby: siRuby,
  'ruby-on-rails': siRubyonrails,
  rust: siRust,
  scala: siScala,
  spring: siSpring,
  sqlite: siSqlite,
  supabase: siSupabase,
  svelte: siSvelte,
  swagger: siSwagger,
  swift: siSwift,
  tailwindcss: siTailwindcss,
  tensorflow: siTensorflow,
  terraform: siTerraform,
  typescript: siTypescript,
  vercel: siVercel,
  vite: siVite,
  vue: siVuedotjs,
  webpack: siWebpack,
  yarn: siYarn,
} satisfies Record<string, SimpleIcon>

export type TechIconName = keyof typeof techIcons

export const techIconColors = Object.fromEntries(
  Object.entries(techIcons).map(([name, icon]) => [name, `#${icon.hex}`]),
) as Record<TechIconName, string>
